apiVersion: v2
name: jenkins-deployment
description: DEP Jenkins
type: application
version: 1.0.0
appVersion: 2.541.1

# Dependencies - Official Jenkins Helm Chart
dependencies:
  - name: jenkins
    version: 5.8.139
    repository: https://charts.jenkins.io
    condition: jenkins.enabled
